# name: my first workflow
# on : push
# jobs:
#     first-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: print hello
#               run: echo "hello world"
            


# name: second workflow
# on: push
# jobs:
#     second-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: download repo
#               uses: actions/checkout@v4
#             - name: show file
#               run: ls
#             - name: show present directory
#               run: pwd


# name: third workflow
# on: push
# jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#             - name: checkout repo
#               uses: actions/checkout@v4
#     test:
#         runs-on: ubuntu-latest
#         steps:
#             - name: print test message
#               run: echo "hello this is a test message"


# name: fourth workflow
# on: push
# jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#             - name: checkout repo
#               uses: actions/checkout@v4
#     test:
#         needs: build
#         runs-on: ubuntu-latest
#         steps:
#             - name: print test message
#               run: echo "hello this is a test message"

#     deploy:
#         needs: test
#         runs-on: ubuntu-latest
#         steps:
#             - name: print test message
#               run: echo "hello this is a deploy message"


name: fourth workflow
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            GREETING: "hello, how are you?"
        steps:
            - name: print greeting
              run: echo $GREETING
    